[package]
name = "config_center"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
fs-err = "2.6.0"
home = "0.5.3"
druid = "0.7.0"